name: ngmlr

channels:
  - conda-forge
  - bioconda

dependencies:
  - python
  - samtools
  - sniffles
  - SURVIVOR
  - igv
  - pbsim2
  - biopython  # for fastq length hist
  - matplotlib # for fastq length hist
  - pandas     # for fastq length hist
